import './globals.css'
import Sidebar from './components/Sidebar'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex bg-[#f5f5f7]">
        <Sidebar />
        <main className="flex-1 ml-64">{children}</main>
      </body>
    </html>
  )
}